 *Artificial Intelligence for Vision & NLP* &nbsp; | &nbsp;  *ATU Donegal - Postgrad Diploma in Big Data Analytics & Artificial Intelligence*

# Student Submisison 
Name           : Selvi Ganesh Kumar                <br>
Student Number : L00196360          <br>
Due Date       : 12th May 2026                <br>
Assignment     :             <br>
Module         : AI for Vision and NLP    <br>
Course         : Postgraduate Diploma in Big Data Analytics and AI

## NLP and Vision Pipeline : High Level
An image of your working pipeline at high level can be inserted here

# Initialisation
Perform pip installs(or use a requirements.txt) <br>
perform imports

## Install packages

In [5]:
# pip installs

requirements = """
opencv-python
pytesseract
numpy
matplotlib
pandas
pymupdf
easyocr
tqdm
pillow
"""

with open("requirements.txt", "w") as f:
    f.write(requirements.strip())

In [6]:
# pip install -r requirements.txt

## Imports

In [8]:
# imports

import os
import re
import zipfile

import numpy as np
import pandas as pd

import cv2
import matplotlib.pyplot as plt

import pytesseract
pytesseract.pytesseract.tesseract_cmd = r"C:\Program Files\Tesseract-OCR\tesseract.exe"

import pymupdf 
import fitz

from tqdm import tqdm

# Support Functions

In [10]:
# code here

def preprocess_image(image):
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    blur = cv2.GaussianBlur(gray, (5,5), 0)
    thresh = cv2.threshold(blur, 150, 255, cv2.THRESH_BINARY)[1]
    return thresh

# NLP

## Sub Heading 1

## code

In [13]:
# The dataset has different filtypes: .jpg (images), .bmp (images) and .pdf (documents)
# ZIP → extract → detect file type → extract text → NLP → output

In [14]:
# STEP 1: Extract ZIP
import zipfile
import os

path = r"C:\Education\M.Sc Documents\Computer Vision & NLP\CA2\images_dataset.zip"

with zipfile.ZipFile(path, "r") as zip_ref:
    zip_ref.extractall("docs")

In [15]:
# To view the extracted files from the zip.

folder = "docs"

for root, dirs, files in os.walk(folder):
    print("Folder:", root)
    print("Files:", files)

Folder: docs
Files: []
Folder: docs\images
Files: ['aloevera_back.jpg', 'architecture_diagram.bmp', 'balck_white_scanned_doc.bmp', 'black_white_doc.pdf', 'car_number_plate.jpg', 'charts_tables.jpg', 'circle_shapes.jpg', 'colour_scanned_doc.bmp', 'colour_scenery.jpg', 'colour_world_map.jpg', 'different_shapes.jpg', 'drawing_face_using_words.bmp', 'drawing_using_words.bmp', 'elephants_photo.jpg', 'first_english_words.bmp', 'handwriting.jpg', 'ink_art_text.bmp', 'inverted_nappy_back.jpg', 'line_photo.jpg', 'olive_oil_front.jpg', 'other_language_scanned.bmp', 'pencil_drawings.bmp', 'pizza_photo.jpg', 'scanned_bill.jpg', 'story_book_images_text.pdf', 'yoga_steps.jpg']

In [16]:
# step 2: Separate file types and storing them in their own variety, for further processing

jpg_files = []
bmp_files = []
pdf_files = []

for root, dirs, files in os.walk(folder):
    for file in files:
        path = os.path.join(root, file)

        if file.lower().endswith((".jpg", ".jpeg", ".png")):
            jpg_files.append(path)

        elif file.lower().endswith(".bmp"):
            bmp_files.append(path)

        elif file.lower().endswith(".pdf"):
            pdf_files.append(path)

print("JPG:", len(jpg_files))
print("BMP:", len(bmp_files))
print("PDF:", len(pdf_files))

JPG: 15
BMP: 9
PDF: 2

In [17]:
# step 3: storing the images in the images files to process images (ocr)

image_files = jpg_files + bmp_files

results = []

for file in image_files:
    img = cv2.imread(file)

    processed = preprocess_image(img)
    custom_config = r'--oem 1 --psm 6'  

    text = pytesseract.image_to_string(processed, config = custom_config)

    results.append({
        "file": file,
        "type": "image",
        "text": text
    })

In this project, a hybrid approach was adopted for processing PDF documents to ensure robust and accurate text extraction across different document types. PDFs can broadly be categorised into two types: text-based PDFs, which contain embedded digital text, and scanned PDFs, which are essentially images of documents and do not contain extractable text. To handle both cases effectively, the system first attempts to extract text directly using PyMuPDF, which is efficient and preserves formatting when digital text is available. If no text is detected on a page (i.e., the extracted content is empty or minimal), the system assumes the page is image-based and applies Optical Character Recognition (OCR) using Tesseract. In this case, the PDF page is converted into an image and processed to extract text. This hybrid strategy improves both performance and accuracy by avoiding unnecessary OCR on text-based documents while still enabling text extraction from scanned or image-based PDFs. It also demonstrates a practical integration of document analysis techniques, aligning with real-world multi-modal document understanding systems.

In [19]:
# handling the pdf files separately, either by converting into image for scanned pdf, or by extracting the text directly, 
# incase of read text based pdf, them the text is extracted:

for file in pdf_files:
    doc = fitz.open(file)
    text = ""

    for page in doc:
        extracted = page.get_text()

        if extracted.strip():
            text += extracted
        else:
            pix = page.get_pixmap(dpi=200)

            img = np.frombuffer(pix.samples, dtype=np.uint8)
            img = img.reshape(pix.height, pix.width, pix.n)
            custom_config = r'--oem 1 --psm 6'  
            text += pytesseract.image_to_string(img, config = custom_config)

        results.append({
            "file": path,
            "type": "pdf",
            "text": text
        })

In [20]:
results

[{'file': 'docs\\images\\aloevera_back.jpg',
  'type': 'image',
  'text': 'See WET JUICE, weit; criabies US to capture trie\nnatural properties of the Aloe vera plant. This\ncooling gel nourishes, soothes and can help |\nrestore dry and problem skin. It can also be\napplied to stretch marks, scars and dry or sun\nexposed skin. |\nNatural actives: Organic Aloe Vera.\nBeneficial properties: Soothing, Cooling,\nRestoring, Nourishing\nDirection ‘ | in, Repeat as often a:\nrequired Over the bod,\n(supery :\nIndicazi § 5 senie la necessit.\n(supervis, ad\nAvvertenz a, =. /contatts con gh accel\n“so ch COM au OLEH Hate, MIO GuUTe cul abbcidante acqua \'\nt POCare SU Cute lesa. IN Caso di rritazione cutanea sospendere «\nconte Tuttliz20 di questo prodotto se. si @ allergic’ a qu.’\non oonente, Tenere lontano dalla portata dei bambini. Conserv"\n4090 fresco e€ asciutto, al riparo dalla luce.\n}\n| Aloe Vera Inner Gel —\n\\ Not fo, intemal\n\\ Ne Water, Dg not Avoid contact with eyes. Ini case of accidental (Ci\nee ths Droduct et 10 open wounds. If sansitivity occurs ce!"\n\\> “FD out of you are allergic or sensitive to any of th":\n. ach of children, Store in a cool tof din\na 4: (- . a cool, dry place ou\n\\ "Cents. cee\ntog ‘ Aloe p. d\n. . " Kay aes (Aloe Vera) Leaf Ol i 5 -\n: a Panthiengy . Alkyl Acrylate a s- ~\n; ; “hg NOxyet Odum Phytate, Sodium On -\nA tf anol Potassitum Sorbate \' _\nve.\n; ‘ i)\n| | LL ’\n¥\nre, .\n'},
 {'file': 'docs\\images\\car_number_plate.jpg',
  'type': 'image',
  'text': 'f eS\nHin gt\n'},
 {'file': 'docs\\images\\charts_tables.jpg',
  'type': 'image',
  'text': 'me 322 =\n—_ == =—\n1 odi Wnt e ‘\na\nVos\noe\n'},
 {'file': 'docs\\images\\circle_shapes.jpg',
  'type': 'image',
  'text': 'a A Py Ago |\nme gS } PE Sh ag\na lll an t\n\n. ve\ney pit 5 ewe, =\n'},
 {'file': 'docs\\images\\colour_scenery.jpg',
  'type': 'image',
  'text': '~— 7\n——_\n,;\n: "wes “eon: * oi\not an ~ ~.\n_ pee - ~\n—_— sm, - |\n=\n. os\n7 ~ oy tO. . ~ :\nw=. — ~ ~\n'},
 {'file': 'docs\\images\\colour_world_map.jpg',
  'type': 'image',
  'text': '—es ~\n~~\nKAZAKHSTAN \\\nta ernovestaw a\ntastany AMER, Act amarien » KOREA\nTURKEY TURKMENISTAN yEnc sour ) ie\nae KOREA 4\nen aso C HINA e\nipa IRAQ TRAN %\ney\nme ae PAKISTAN ~*~, BHUTAN .\nSAUDI “CXy\nARABIA TAIWAN\n2 INDIA ncis MYANMAR f Ww “ -\noe ah ‘ .\na i"\nast im PTNAM . .\nMoy PHILIPPINES\nry\nSRI > / t.\nLANKA ae\nMALDIVES oe\n; A AL ‘SO\n. scare yy\n; wt | * |\n5 4 ao thy\nIN DO ES IA 4\n“Decorigg . s\n'},
 {'file': 'docs\\images\\different_shapes.jpg',
  'type': 'image',
  'text': 'cece © wsuuse ‘ Z\nress . Zz\n7 MII SR LZ\n'},
 {'file': 'docs\\images\\elephants_photo.jpg',
  'type': 'image',
  'text': "~ hd ‘ Ped Bele Se ether nn, wa\ni) ~ MM . « 'y . ft : . e\nCo re Noa ~h.. ~ . - -- *t A ape oe we . we f. ° ’ ~, \\\n. ~ ? J ‘ reo See ge: ' e Os . . :\nan 7 + ‘*. ae ws : Veow ° ao a a al Pal .\n. Res sae ee by OS, VN\nm 2 ve ‘i Wee UJ <a :\nft: <2 oe i) . a 4 ws Oo IE We ay .\ne ios rake oe | - se oe? 2 if _ hae es ; i. .\n-. Sen) ae: wen : 7 gS Cte ae\n“2 ° Doe oe AHS we FPP ee RRA oe\n2r- ars Ve eS Fo Rate “ pyrctes wt a Vee\nyas . oe ap toe 2% Diets Jey y “aia : . wey et ee ‘\nwoe Oe eo one . a aon. ae ~~ of : ~ -_& .\n‘ * Aan CATES ay Oe aa - aes pare;\n‘ . Cas . pg A Y -- ~~\nus a $ ore PaaS S Mr iSt ck . ' : Swe\nSythe Poke igh Re 1oTtO : b4 ay\nDh vy yaaa as Credit: BlueBarronPhot °\nry tines = Y “7. “sae 4 J ii\n_ ts eats ae x\nEo 2 ing . a\n59488927 Leas Se : .\n"},
 {'file': 'docs\\images\\handwriting.jpg',
  'type': 'image',
  'text': ". ee nes ne lotertace Conse 7 me oe\nBaeeay Syste powered whic are  Nunenes) tae\nBe UY ‘ mean of a eta: -\ni Purpose of this System ” .\nRS to  anolyce. These em adding? axe.\nq an ds me Ne ckor databogs\nAcademic PoreY on lage Sroyed 5\nlanquage models and Be | eshign allows 4h? SyeP A\nay Rene dhe. j\nol o ports oS big\nUSex Content DAtrictly based most yereven SOS\nS hen On|\noq =the Conte at Of the the docume vit , a\n\\o achieve. tS, T Useck oa Ered ding go vole ' 1 a\nRetrieval - Quoymented qenerattc nit A ty Bae xeleyari z\nApproach ; wrrich @ NRUKER tral content od 2\ntee onodel does uct ely The LLM aes é\non eo xtexnal Knowledge » [4s Llores enn\nout Instead genewel> | Tocally though OThegiaal\nanswers only Pron < pt al ae\n¢ wdead document , Oe {ne a) ear\nbo, the RAG pipeline 3 d he pigeied\nCortex +\nak Neck, the PDE doc umeat text\n1S loaded and spite tnto\nmailer Chunks of text\n"},
 {'file': 'docs\\images\\inverted_nappy_back.jpg',
  'type': 'image',
  'text': "ee a, el ee\n2¢ od i ail aan Bae &\nuy ee } a Bar!\n: oc //t~ - -\nS7 Ww wow - F\n, “4 ell , 1\nky “ “4 ? c . . = “\ni A ‘\\ a . ; . &\n3& ed . 2 =\n-8 ° > oy - f =\ney = \\ 4 4 ASA ‘\n3 @ go \\-> fi\n<ge A ond\na: < . ae\n$335 SS —\n: s32 ry .\n' gist ° e- s X\nim <i¢3 = * yy 2\n_ $3 cf $ FA - Z fe) ~~)\n7 a < , :\nage , >\n. i _£-\n"},
 {'file': 'docs\\images\\line_photo.jpg',
  'type': 'image',
  'text': 'on a A - . 4\na - 7 wert . - a7 —\n—— ny - a So = fo . ar SL oe\n= ~sS,, ..\nTARE iStock\n7 Credit: NanoStockk\n“an f\non of\n- a !\n624183176 aan\n'},
 {'file': 'docs\\images\\olive_oil_front.jpg',
  'type': 'image',
  'text': ', Ve\n| * “\na :\na“\na\n'},
 {'file': 'docs\\images\\pizza_photo.jpg',
  'type': 'image',
  'text': 'adr "5 ~— “\nAct =\nTA = —=<S—3 BLA;\n- - . “a ‘“ = _ “ rs | LY, eS wy ee\nne Ri . \\yns 4 Qos Aa " 2 a’? " yt ——\n» eo Tal toa ~N —<— - er ey tare!\noo ae LIS Ly SE ss t= SRA:\nTine! es Se 6 ae) Ne ee:\n‘ao Ae - —- ~* ~ ng rs ‘ = . ~\nSE Sam 2a. Ss RBA \\~ a\nSO Sh, OO SA ES":\n~. ‘ ee, io, \' ot ois ha hs cal < Sina 1 ete ag Wes SY No\nH.- ro: L242 : a tay Sie > see 2 a ae\ntee 3 iz) ; : ee 4 » rey ay 2 “\neee) en Si 7S ee Ase), Sr ce ae\nEN od hele! < oy\nma Sal al Lay | A : Gran . x tt, <i fh CS te\nme A BOSS 1 \\Or king 1 Fe ~ on\nTe ~% aan ’ log 2. wv "=o v dver. -_ \\e Flee A Co\nie ee AE Oy ee a See Seen i\nak ie faces $e SN Ce Lan we ’ BO 0 os\ni “ SPAS C Cpe teen) 7 en nf eae\nSs “Sy eyed 3e sey Ce ane -? | eae ce. ae NO ae\n— a. . P ay ena . we j ‘ "2 “ eae ky... aa . @\n: pe x ny A y a | oa a) a oo ) ea\noe eo 4 "pet pee - - + a - . . a\n. wife 4 a hoe ; y Fr | ae eS oe rain 3\n8 ? yaar MO: s : an a Re » ae Se \\ 2 ” a “& et\nte ee 58" ay ae . 3 — _ oi é ” fe 7.\nSau BAS. \\ ee. Li ‘ee: soe _~ ae OE\na. ee ak Ae Sex? ay, Nia ANT\n<2 NS er PRA a, 8 Co ger\naw ret $2 a ® j , ry " aN\n~ Oth: Oe he: ON Ce lap SP 9S on\nen Co witt, ss 2: iy me mov ae eat ESS\nmeee = 4 pets Tt ee Site oo)\n'},
 {'file': 'docs\\images\\scanned_bill.jpg',
  'type': 'image',
  'text': 'uti WWMM wnt\n'},
 {'file': 'docs\\images\\yoga_steps.jpg',
  'type': 'image',
  'text': '— Bt ie:\nagen a sigs. “\ntt | rt 7\nalts\n4 ‘ i ti a\ne { 3 ; z t i |\n. eet wa\n= 2% a at E3\ncn e Aa 35 ee\nope EOE ;\n> 2 8 "ako ot a\n$4 ¢ -- tT 5 yl\né 3 a 2 pang > gare ~ rE EE\nggi2g Th ih ate\npiaae Uo ua ul g\ne2aGR aap ouu one 4\n~<a 3 3 .\n4 a a E a eT\n2 2 \\ be\n'},
 {'file': 'docs\\images\\architecture_diagram.bmp',
  'type': 'image',
  'text': 'Information {Meme cs :\nBranches Systems : io\n. 1 : Enterprise Service Bus ““yctnmrt| nrg weet aA nt\nimemet |! acer] eee e|\nH £ Cuommar |) ftateematien Servo Ut ui one :\nes | Sh) - dee eT\nAgents ba permet — oF ae ce Te\nH H  Omewey |i > Lm . , Pr Sggary\n: : i ree [tt ae :\ntome fe a cas tas | Unvstrut tured |\nBanting | t ‘ {Customer ; wa ae | baa}\n: ‘ pinagnea ft a a :\n. set eweescee { Analrtes: pt Oma ;\nSecurity, Management & Governance\nRapid Development & Integration\n'},
 {'file': 'docs\\images\\balck_white_scanned_doc.bmp',
  'type': 'image',
  'text': 'A Vad\nBuildings and oo : | ; hi py\nen ee alee ae\nee xo ‘ f » J} A ‘ 7; eee i ?\nied Vf t y, Le go A eo s ‘ mo i °\nDU DORE iter Sc aN i: oc\ncen? ne ean va Ria\n'},
 {'file': 'docs\\images\\colour_scanned_doc.bmp',
  'type': 'image',
  'text': 'Landscapes\n. ste\nCityscapes : ae\n‘fey . sary et at\nweit, OF es.\n54\n'},
 {'file': 'docs\\images\\drawing_face_using_words.bmp',
  'type': 'image',
  'text': 'fetal\nURN\nSVG Files]\nyt GF THE Woy,\nwll tmnt,\nzz Os TL ¢,{G\nPAA OF G88 Sp yb,\nKINOEZ ORT LOWY. 2.\nngs 2,7 Arn MN Egg &\nwae OF UMNO ZN MNES\nrt ne TY » 7D, t = e Le -\nGugh SW Lei 1, WN) aeseeMty\nMLPEER Ap REE al\nree OF ihs W\'s\ndpgisoo ny, 52%\na = “My, $23\n= = Wor “ mente = 2\n° gy Ss ENS 2G Se\n5a 3 é yee"\n5 a ORR, Fee Ee\nGF & Scent =\n2S"\n"SVG DXF PNG EPS] Sihouette tudio@ Cricut Desin Space ©)\n'},
 {'file': 'docs\\images\\drawing_using_words.bmp',
  'type': 'image',
  'text': 'Yt She\nSe A ge ee 9 tok gi aa\nvie? i Been whe 6 oe dass bam\nBet ales f fe ¢ wr)\nSORE IN N AS etrhy yea\nBet gentene ye _ NS\nVISA ee ss\nSRE ec OR Ss Coa ee\nRiley waft 25 Og foo Fou = 0\nhe ar FS aid se\n\n$e. aetey ry NO o gg F -_ FP | ai\n'},
 {'file': 'docs\\images\\first_english_words.bmp',
  'type': 'image',
  'text': "100 Garden To Classroom\n\nAah A ede 1 eee\nENGLISH [A Pp ia ae aes\nGoraen met fence f cloudy thunder _— butcher berber\nPicture ai area bee a 2\nVOCABULARY [aart tiieemliind ~ (a @ cxgrten “pt\n¥ . ‘ 5 —~ — ' i. &\n= Cg rn 7 le - ER\n. —— : dé.\nmes = y|S- 23\n\nworeengihen.com { t 1 weew.englishan.com t\n"},
 {'file': 'docs\\images\\ink_art_text.bmp',
  'type': 'image',
  'text': 'B Using Quink ink ~ | ?\na - 47> °¥ “\n- 1 4 4 t\n. Pd ‘Y\n'},
 {'file': 'docs\\images\\other_language_scanned.bmp',
  'type': 'image',
  'text': 'BAAE Sham\nPee ey\nWe litte\n'},
 {'file': 'docs\\images\\pencil_drawings.bmp',
  'type': 'image',
  'text': 'Poe “ae =e\n= - oe ee “4 5 Se\n>\n” a 7] R\n'},
 {'file': 'docs\\images\\yoga_steps.jpg',
  'type': 'pdf',
  'text': ')\nFamous Artists Cartoon Course\nWestport, Connecticut\n)\ne\nThe comic head -[\nRube Goldberg\nMilton Caniff\n“ Al Capp\nHarry Haenigsen\nWillard Mullin\nGurney Williams\nDick Cavalli\nWhitney Darrow, Jr.\nVirgil Partch\nBarney Tobey\n( Copyright © 1956, 1965 Famous Artists arconicoran ina\n'},
 {'file': 'docs\\images\\yoga_steps.jpg',
  'type': 'pdf',
  'text': ')\nFamous Artists Cartoon Course\nWestport, Connecticut\n)\ne\nThe comic head -[\nRube Goldberg\nMilton Caniff\n“ Al Capp\nHarry Haenigsen\nWillard Mullin\nGurney Williams\nDick Cavalli\nWhitney Darrow, Jr.\nVirgil Partch\nBarney Tobey\n( Copyright © 1956, 1965 Famous Artists arconicoran ina\nfi . { 1 a 4 j bo r SWRLS a\neS Ba Neo 45, \\ e\n\\% hay? Ke ; =\nLU } oui Ss\nBy = < A Smee “4\nX Flak > SS) Sa : Say K x iS =\né Si torts pe ge A a ww\nVT ee\n= _ S&S\n“A £ ? a i J " \\ V4 we S “N t\ny N ees J ~ ‘, \\ ~ ‘ SL. \\\\\n* pcre ny hss a oll i * ) \\\nline around it to locate the eyes and ears, and another line tA\nwes Censeal ss Coe Conca Beas a ever tae >\n'},
 {'file': 'docs\\images\\yoga_steps.jpg',
  'type': 'pdf',
  'text': ')\nFamous Artists Cartoon Course\nWestport, Connecticut\n)\ne\nThe comic head -[\nRube Goldberg\nMilton Caniff\n“ Al Capp\nHarry Haenigsen\nWillard Mullin\nGurney Williams\nDick Cavalli\nWhitney Darrow, Jr.\nVirgil Partch\nBarney Tobey\n( Copyright © 1956, 1965 Famous Artists arconicoran ina\nfi . { 1 a 4 j bo r SWRLS a\neS Ba Neo 45, \\ e\n\\% hay? Ke ; =\nLU } oui Ss\nBy = < A Smee “4\nX Flak > SS) Sa : Say K x iS =\né Si torts pe ge A a ww\nVT ee\n= _ S&S\n“A £ ? a i J " \\ V4 we S “N t\ny N ees J ~ ‘, \\ ~ ‘ SL. \\\\\n* pcre ny hss a oll i * ) \\\nline around it to locate the eyes and ears, and another line tA\nwes Censeal ss Coe Conca Beas a ever tae >\n3\n)\n°\nThe comic head\nWhen you meet a friend the first thing you look at is his face. try to make a perfect single-line balloon or oval, or draw the\nYou say, “You look fine” or “You look sick” or “You look sad” balloon with a compass. Do them freehand. The pencil work is\nor “You look happy.” You recognize Joe or Bill or Mary by the only a guide upon which you will construct the cartoon head. If\neyes or nose or ears or hair. The good Lord is an expert at put- it is a little lopsided or bumps out on the side, don’t worry about\nting people together so you can identify them easily. Each of us it. Sometimes these irregularities will suggest an entirely new\nhas different features — even twins are not really identical — and, type of character to you. Also, when drawing the balloon out-\nin addition, each of us has a definite and individual personality. line, do not get in the habit of bearing down too heavily with\n) As an observer and recorder of the human race, you must have your pencil. In later lessons, to finish your cartoons, you will go\nan awareness not only of the surface differences between people over their outlines in ink; if your penciling is too dark, it will\nbut also of what makes them tick. In general, you must become be almost impossible to erase after inking.\na psychologist. A good understanding of the emotional differ- The important thing to remember when drawing any cartoon\nences between people will help you to create cartoon characters is to keep it simple. The simple, direct approach of cartooning\nthat will react properly to any set of circumstances and leave no has an instantaneous effect upon an audience. Because of its\ndoubt in the reader’s mind as to the type of people they are. directness and clarity, the cartoon has become well established\nFrom now on we want you to start thinking like a cartoonist. in every field of visual communication, including television and\nStop looking at your friends as Joe, Bill or Mary. Instead, think advertising. Keep in mind the importance of the simple, direct\nof them as Joe, the big-mouthed showoff; Bill, the little mouse; approach when you draw the cartoon heads for this lesson. Strive\nand Mary, the girl that’s afraid of her husband, kids and the constantly to capture, in as few and as simple lines as possible,\nfamily goldfish. Open your eyes and see the people around you. the personality and feeling of the character you are drawing.\nWatch and study their actions and reactions. The painter hires Avoid overdrawing or shading, particularly in the cartoon face.\nmodels to pose for him, but you, as a cartoonist, want no planned Remember that too many fine lines, instead of strengthening an\nposes. You want your models to act naturally against a natural expression, will often kill it. Make simplicity your watchword.\nbackground. So wherever you are, at work, at play or at the Many times throughout your Course we will remind you of\nsupermarket, keep your eyes and your mind open — your eyes to the importance of practice. We particularly stress it here because\nstudy the physical differences and your mind to gain an under- __ the cartoon head is so basic. By practice we do not mean that\nstanding of your subjects’ personalities. you are to spend only ten or fifteen minutes a day at your\nBecause the face and head are the most expressive parts of the _ studies. We mean that you should draw every chance you get.\nfigure, we naturally take them up first. The method we use to Form right now the habit of carrying a sketch pad with you\n( draw them may appear simple, but please remember that every wherever you go. Sketch pads come in all sizes, and there is a\nhead or face, from the simple exaggerated cartoon head to the _ small size that will fit in a coat pocket or a handbag. Every time\nvery realistic head of the illustration and adventure-strip type, _ you see an interesting face, jot it down in a quick sketch. Don’t\nis built upon the same basic principles. All heads are shaped stiffen up and make work of it or worry about producing a\nsomewhat like a balloon and have two eyes, two ears, one nose _ clean, finished pencil drawing. You are interested in capturing\nand one mouth. In the pure comic or highly stylized type, these _a character or an expression, and a fast sketch will often do that\nfeatures may be exaggerated or even placed in extreme positions _ better than a painstaking drawing. If you are all alone in the\nin relation to each other, but the basic principles of head con- __ dentist\'s waiting room and there are no models present, just draw\nstruction are still the same as those used to draw the realistic faces from memory. The important point is to keep drawing.\ntype. Page 10 illustrates this basic relationship of all cartoon Learning to draw cartoons is a serious business. Fortunately,\nheads. Study it carefully and note how each of the different men however, there is just as much pleasure in it as there is work.\nhas made use of the same basic principles and features to create Cartooning has often been called “the happy art,” and drawing\nhis own individual characters. comic heads is one of the happiest parts of it. So grab a pencil\nIn starting to draw the cartoon head, think of it as being like and start swinging them in. Don’t expect every head you draw\na child’s balloon — something that has thickness as well as height to be a masterpiece — but do expect them to get better as you\nand width. The photo of the balloon on the opposite page will give them more time and thought — and, above all, have fun\ndemonstrate what we mean. The balloon has depth —a third drawing them! :\ndimension. If you let yourself think of it as a flat circle, you will For this first lesson, all the materials you need are some soft\nend up with a lot of characters drawn without any feeling of pencils (2B or 3B), some 814 x 11-inch Bond typing paper, and\nsolidity. Remember that the head is a sphere and, when the fea- an Artgum or kneaded rubber eraser, and you are ready to go\ntures are placed on its surface properly, they will give the effect to work. Remember, when buying supplies, that a good crafts-\n4 of being drawn on a curve rather than a flat plane. man likes to use good tools. Luckily for the cartoonist, pencils\nGet in the habit of dashing your balloons off freely. Let your are inexpensive. When one gets too short for comfort, throw it\npencil go around the balloon shape three or four times. Don’t away or give it to the ladies’ bridge club.\n'},
 {'file': 'docs\\images\\yoga_steps.jpg',
  'type': 'pdf',

In [21]:
# Creating a dataframe for the purpose of organising the above results

In [22]:
results_df = pd.DataFrame(results)

results_df

,file,type,text
0,docs\images\aloevera_back.jpg,image,"See WET JUICE, weit; criabies US to capture tr..."
1,docs\images\car_number_plate.jpg,image,f eS\nHin gt\n
2,docs\images\charts_tables.jpg,image,me 322 =\n—_ == =—\n1 odi Wnt e ‘\na\nVos\noe\n
3,docs\images\circle_shapes.jpg,image,a A Py Ago |\nme gS } PE Sh ag\na lll an t\n\n...
4,docs\images\colour_scenery.jpg,image,"~— 7\n——_\n,;\n: ""wes “eon: * oi\not an ~ ~.\n..."
...,...,...,...
64,docs\images\yoga_steps.jpg,pdf,By T. Albert\nIllustrated by: maaillustrations...
65,docs\images\yoga_steps.jpg,pdf,By T. Albert\nIllustrated by: maaillustrations...
66,docs\images\yoga_steps.jpg,pdf,By T. Albert\nIllustrated by: maaillustrations...
67,docs\images\yoga_steps.jpg,pdf,By T. Albert\nIllustrated by: maaillustrations...
68,docs\images\yoga_steps.jpg,pdf,By T. Albert\nIllustrated by: maaillustrations...

The dataset contains a collection of mixed document types, including images and PDF files, all processed into a unified format for analysis. Each row represents a single document instance where the extracted text is obtained using OCR for images and a combination of direct text extraction and OCR fallback for PDFs. This allows both visual and textual content to be converted into machine-readable form. The resulting structure supports further NLP tasks such as text cleaning, feature extraction, and document understanding across heterogeneous sources within a single consistent dataset.

In [25]:

for file in pdf_files:
    doc = fitz.open(file)

    for page_num, page in enumerate(doc, start=1):
        text = page.get_text()

        # If text exists
        if text.strip():
            extracted_text = text

        # fallback OCR
        else:
            pix = page.get_pixmap(dpi=200)
            img = np.frombuffer(pix.samples, dtype=np.uint8)
            img = img.reshape(pix.height, pix.width, pix.n)

            custom_config = r'--oem 1 --psm 6'
            extracted_text = pytesseract.image_to_string(img, config=custom_config)

        results.append({
            "file": file,
            "page": page_num,
            "type": "pdf",
            "text": extracted_text
        })

In [26]:
results.append({
    "file": file,
    "page": page_num,   # None for images
    "type": "pdf" or "image",
    "text": extracted_text
})

results1_df = pd.DataFrame(results)

results1_df

results1_df

,file,type,text,page
0,docs\images\aloevera_back.jpg,image,"See WET JUICE, weit; criabies US to capture tr...",NaN
1,docs\images\car_number_plate.jpg,image,f eS\nHin gt\n,NaN
2,docs\images\charts_tables.jpg,image,me 322 =\n—_ == =—\n1 odi Wnt e ‘\na\nVos\noe\n,NaN
3,docs\images\circle_shapes.jpg,image,a A Py Ago |\nme gS } PE Sh ag\na lll an t\n\n...,NaN
4,docs\images\colour_scenery.jpg,image,"~— 7\n——_\n,;\n: ""wes “eon: * oi\not an ~ ~.\n...",NaN
...,...,...,...,...
110,docs\images\story_book_images_text.pdf,pdf,"“Arrgh, and now lad it’s up to ye to do the ri...",31.0
111,docs\images\story_book_images_text.pdf,pdf,“I think we should give the rest to the local ...,32.0
112,docs\images\story_book_images_text.pdf,pdf,"Your Story Book!\nA book specially made, with ...",33.0
113,docs\images\story_book_images_text.pdf,pdf,An exciting story that has everything that chi...,34.0
114,docs\images\story_book_images_text.pdf,pdf,An exciting story that has everything that chi...,34.0

In [27]:
# step 6: NLP

texts = [item["text"] for item in results]

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
X = tfidf.fit_transform(texts)

ModuleNotFoundError: No module named 'sklearn'

# Vision

## Sub Heading 1

In [ ]:
# code here...

# Multi-modal

## Sub Heading 1

In [ ]:
# code here

# Final Output

In [ ]:
# code